### Login => Not in db
POST localhost:5000/facilities/login
content-Type: application/json

{
  "mail": "notInDb",
  "password": "azerty1."
}

### Get all facilities
GET localhost:5000/facilities

### Login => In db wrong password
POST localhost:5000/facilities/login
content-Type: application/json

{
  "mail": "jess@mail.com",
  "password": "AZERty1."
}

### Login => In db correct password
POST localhost:5000/facilities/login
content-Type: application/json

{
  "mail": "jess@mail.com",
  "password": "azerty1."
}

### Register
POST localhost:5000/facilities/register
content-Type: application/json

{
  "name": "Facility#3",
  "address": "Rue de la paix, 23",
  "mail": "jess@mail.com",
  "password": "azerty1.",
  "is_doctor": false
}

### Insert Qrcode
POST localhost:5000/qrcodes
content-type: application/json

{
  "location_id": "123"
}
